Added error message to log E2E test failures for easier debugging and ensure we’re not breaking anything.

diff --git a/.pipelines/ci.yml b/.pipelines/ci.yml
--- a/.pipelines/ci.yml
+++ b/.pipelines/ci.yml
@@ -178,6 +178,13 @@ stages:
               deploy_e2e_db
               register_sub
               docker compose up e2e
+              # Check if the E2E tests failed
+              if [ $E2E_EXIT_CODE -ne 0 ]; then
+                echo "##vso[task.logissue type=error] E2E tests failed. Check the logs for more details."
+                exit 1
+              else
+                echo "E2E tests passed."
+              fi
             displayName: ⚙️  Run E2E Test Suite
 
           # Log the output from the services in case of failure
