test e2e in single job
Signed-off-by: Karan.Magdani <kmagdani@redhat.com>

diff --git a/.pipelines/e2e.yml b/.pipelines/e2e.yml
--- a/.pipelines/e2e.yml
+++ b/.pipelines/e2e.yml
@@ -52,5 +52,23 @@ jobs:
       register_sub
 
       export CI=true
-      make test-e2e
+      if make test-e2e;
+      then
+        echo "E2E Pass, Skipping must-gather"
+        echo "##vso[task.setvariable variable=mustGather]No
+      else
+        echo "E2E Failed, need must-gather"
+        echo "##vso[task.setvariable variable=mustGather]Yes
+  - script: |
+      set -e
+      wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.9.8/openshift-client-linux-4.9.8.tar.gz
+      tar xf openshift-client-linux-4.9.8.tar.gz
+      make admin.kubeconfig
+      export KUBECONFIG=admin.kubeconfig
+      ./oc adm must-gather
+      tar cf must-gather-$CLUSTER.tar.gz must-gather.local.*
+    condition: eq(variables['mustGather'], 'Yes')
+    displayName: "Need Must Gather"
+    publish: /home/cloud-user/must-gather.tar.gz
+    artifact: must-gather
   - template: ./templates/template-az-cli-logout.yml
